# @name Upload File

POST http://localhost:3000/file-upload
Content-Type: multipart/form-data; boundary=----file-boundary

------file-boundary
Content-Disposition: form-data; name="text"

title
------file-boundary
Content-Disposition: form-data; name="file"; filename="teste.csv"
Content-Type: text/plain

< ./teste.csv
------file-boundary--