# @name Upload File

POST {{host}}/upload
Content-Type: multipart/form-data; boundary=----file-boundary

------file-boundary
Content-Disposition: form-data; name="text"

title
------file-boundary
Content-Disposition: form-data; name="image"; filename="1.png"
Content-Type: text/plain

< ./teste.csv
------file-boundary--