# @name UploadFile

POST {{host}}/file-upload
Content-Type: multipart/form-data; boundary=----file-boundary

------file-boundary
Content-Disposition: form-data; name="text"

title
------file-boundary
Content-Disposition: form-data; name="files"; filename="teste-mega.csv"
Content-Type: text/plain

< ./teste-mega.csv
------file-boundary--