# @name Metrics-MRR

GET {{host}}/metrics/65afb49a603cd719b5d72037/mrr
Content-Type: application/json

### 

# @name Metrics-CHURN

GET {{host}}/metrics/65af1afa30d9f34769997c36/churn-rate
Content-Type: application/json

### 

# @name Metrics-Group-by-Status

GET {{host}}/metrics/65af1afa30d9f34769997c36/group-by-status
Content-Type: application/json

###

# @name Metrics-Group-by-Status

GET {{host}}/metrics/65af1afa30d9f34769997c36/group-by-users-per-value
Content-Type: application/json