version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=senha
    ports:
      - '27017:27017'

  # app:
  #   image: app
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  #   networks:
  #     - mongo

volumes:
  mongodb-data:
